displayName: Ontada Support Agent
schemaName: cr52a_supportAgent
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cr52a_supportAgent.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: false
    contentModeration: High
    optInUseLatestModels: false

publishedOn: 2026-01-07T15:32:41.0000000Z
template: default-2.1.0
language: 1033