displayName: Biostat_Data_Agent
schemaName: copilots_header_b109f
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    default-2.1.0:
      content:
        capabilities:
          $kind: GptCapabilities
          diagnostics:
          webBrowsing: true

        conversationStarters:
        description:
        displayName: Agent
        instructions:

      spec:
        connectors:

    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnCreate: false
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: copilots_header_b109f.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-01-21T21:30:23.0000000Z
template: default-2.1.0
language: 1033